[workspace]
resolver = "3"

members = ["crates/lib", "crates/main", "crates/testing"]
exclude = ["dep"]

[profile.release]
debug = 2
lto = true
opt-level = 'z'

[profile.dev]
debug = 2
lto = true
opt-level = "z"
