[workspace]
resolver = "3"

members = ["crates/lib", "crates/main"]
exclude = ["dep"]

[profile.release]
debug = 2
lto = true
opt-level = 'z'

[profile.release.package."*"]
opt-level = 3

[profile.dev]
debug = 2
lto = true
opt-level = "z"
