[workspace]
resolver = "3"

members = ["crates/backend", "crates/lib", "crates/main"]
exclude = ["dep"]

[profile.release]
opt-level = "z"
lto = "fat"
debug = "full"
codegen-units = 1

[profile.release.package."*"]
opt-level = 3

[profile.dev]
opt-level = "z"
lto = "fat"
debug = "full"
