name: Docs

on:
  push:
    branches: [main]

env:
  BUILDER_THREADS: '1'

jobs:
  book:
    runs-on: ubuntu-latest

    # This will ensure at most one doc build job is running at a time
    # If another job is already running, the new job will wait.
    # If another job is already waiting, it'll be canceled.
    # This means some commits will be skipped, but that's fine because
    # we only care that the latest gets built.
    concurrency: book

    steps:
      - uses: actions/checkout@v2
      - name: Install asciidoctor
        run: |
          sudo apt-get install asciidoctor

      - name: build
        run: |
          cd docs
          make

      - name: upload
        run: |
          mkdir -p build
          mv docs/book build/trouble
          tar -C build -cf trouble.tar trouble
          .ci/book.sh
        env:
          KUBECONFIG: ${{secrets.KUBECONFIG}}
  doc:
    runs-on: ubuntu-latest

    # This will ensure at most one doc build job is running at a time
    # If another job is already running, the new job will wait.
    # If another job is already waiting, it'll be canceled.
    # This means some commits will be skipped, but that's fine because
    # we only care that the latest gets built.
    concurrency: doc

    steps:
      - uses: actions/checkout@v2
      - name: Install docserver
        run: |
          wget -q -O /usr/local/bin/docserver-builder "https://github.com/embassy-rs/docserver/releases/download/v0.5/builder"
          chmod +x /usr/local/bin/docserver-builder

      - name: build
        run: |
          mv rust-toolchain-nightly.toml rust-toolchain.toml
          mkdir crates
          docserver-builder -i host -o crates/trouble-host/git.zup

      - name: upload
        run: |
          .ci/doc.sh
        env:
          KUBECONFIG: ${{secrets.KUBECONFIG}}
